# Generated by Django 6.0.1 on 2026-01-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PickupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=80)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('waste_type', models.CharField(choices=[('WET', 'Wet'), ('DRY', 'Dry'), ('EWASTE', 'E-waste'), ('HAZARD', 'Hazard')], max_length=10)),
                ('quantity', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
                ('address', models.CharField(max_length=200)),
                ('slot', models.CharField(default='Morning', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='waste_photos/')),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('ASSIGNED', 'Assigned'), ('PICKED', 'Picked')], default='REQUESTED', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WasteGuideItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=80, unique=True)),
                ('category', models.CharField(choices=[('WET', 'Wet'), ('DRY', 'Dry'), ('EWASTE', 'E-waste'), ('HAZARD', 'Hazard')], max_length=10)),
                ('instructions', models.CharField(max_length=220)),
            ],
        ),
    ]
